package interfaces;

import controle.controladorSobre;
import controle.controladorAtalhos;

import entidade.Senha;
import entidade.Visão;
import entidade.Usuário;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.net.URL;

import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

 /*
 * @author Cassiano Rogério
 */

//Janela principal do programa de gestão de senhas
@SuppressWarnings({ "serial", "unused" })
public class Blu extends javax.swing.JFrame {
    /**
    * Gestor de senhas desenvolvido por Cassiano Rogério.
    */
    String userLogado = null;
    
    public Blu(String nomeUser) {
        userLogado = nomeUser;
        URL url = this.getClass().getResource("/images/key 20x20.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        initComponents();
        //Quando for dado um clique duplo na lista de cadastros abre a janela de visualização do cadastro clicado duplamente
        //cliqueDuplo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListagem = new javax.swing.JPanel();
        jScrollPaneListadeSenhas = new javax.swing.JScrollPane();
        jLabelFundoListagem = new javax.swing.JLabel();
        jPanelBotões = new javax.swing.JPanel();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBarMenus = new javax.swing.JMenuBar();
        jMenuMenuUsuário = new javax.swing.JMenu();
        jMenuItemGerenciar = new javax.swing.JMenuItem();
        jMenuItemTrocar_Usuário = new javax.swing.JMenuItem();
        jMenuItemBotão_Sair = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuItemAtalhos = new javax.swing.JMenuItem();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blu");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(getExtendedState());
        setLocation(new java.awt.Point(0, 0));
        setMaximizedBounds(getMaximizedBounds());
        setMinimumSize(getMinimumSize());
        setName("Blu"); // NOI18N
        setShape(getShape());
        setSize(getMaximumSize());

        jPanelListagem.setBackground(new java.awt.Color(204, 204, 204));
        jPanelListagem.setMaximumSize(getMaximumSize());
        jPanelListagem.setLayout(new javax.swing.OverlayLayout(jPanelListagem));

        jScrollPaneListadeSenhas.setOpaque(false);
        jScrollPaneListadeSenhas.getViewport().setOpaque(false);
        jScrollPaneListadeSenhas.setMaximumSize(getMaximumSize());

        jPanelListagem.add(jScrollPaneListadeSenhas);

        jLabelFundoListagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFundoListagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Key backgroung 250x250.png"))); // NOI18N
        jLabelFundoListagem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelFundoListagem.setFocusable(false);
        jLabelFundoListagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelFundoListagem.setInheritsPopupMenu(false);
        jLabelFundoListagem.setMaximumSize(getMaximumSize());
        jLabelFundoListagem.setMinimumSize(getMinimumSize());
        jLabelFundoListagem.setPreferredSize(getPreferredSize());
        jLabelFundoListagem.setRequestFocusEnabled(false);
        jLabelFundoListagem.setVerifyInputWhenFocusTarget(false);
        jPanelListagem.add(jLabelFundoListagem);

        getContentPane().add(jPanelListagem, java.awt.BorderLayout.CENTER);

        jButtonSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit 40x40.png"))); // NOI18N
        jButtonSair.setMnemonic('s');
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabel1.setText("Blu - Sistema de gerenciamento de estoque e vendas");

        javax.swing.GroupLayout jPanelBotõesLayout = new javax.swing.GroupLayout(jPanelBotões);
        jPanelBotõesLayout.setHorizontalGroup(
        	jPanelBotõesLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanelBotõesLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGap(637)
        			.addComponent(jButtonSair)
        			.addContainerGap())
        );
        jPanelBotõesLayout.setVerticalGroup(
        	jPanelBotõesLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanelBotõesLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanelBotõesLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanelBotõesLayout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
        				.addGroup(jPanelBotõesLayout.createSequentialGroup()
        					.addComponent(jButtonSair)
        					.addGap(0, 0, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        jPanelBotões.setLayout(jPanelBotõesLayout);

        getContentPane().add(jPanelBotões, java.awt.BorderLayout.SOUTH);

        jMenuBarMenus.setBorder(null);
        jMenuBarMenus.setFocusCycleRoot(true);
        jMenuBarMenus.setName(""); // NOI18N
        jMenuBarMenus.setPreferredSize(new java.awt.Dimension(50, 22));

        jMenuMenuUsuário.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuMenuUsuário.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user 20x20.png"))); // NOI18N
        jMenuMenuUsuário.setMnemonic('u');
        jMenuMenuUsuário.setText(userLogado);
        jMenuMenuUsuário.setFocusable(false);
        jMenuMenuUsuário.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        jMenuItemGerenciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user 20x20.png"))); // NOI18N
        jMenuItemGerenciar.setText("Gerenciar");
        jMenuItemGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarActionPerformed(evt);
            }
        });
        jMenuMenuUsuário.add(jMenuItemGerenciar);

        jMenuItemTrocar_Usuário.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users 20x20.png"))); // NOI18N
        jMenuItemTrocar_Usuário.setText("Trocar Usuário");
        jMenuItemTrocar_Usuário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTrocar_UsuárioActionPerformed(evt);
            }
        });
        jMenuMenuUsuário.add(jMenuItemTrocar_Usuário);

        jMenuItemBotão_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit 20x20.png"))); // NOI18N
        jMenuItemBotão_Sair.setText("Sair");
        jMenuItemBotão_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBotão_SairActionPerformed(evt);
            }
        });
        jMenuMenuUsuário.add(jMenuItemBotão_Sair);

        jMenuBarMenus.add(jMenuMenuUsuário);

        jMenuSobre.setBorder(null);
        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about 20x20.png"))); // NOI18N
        jMenuSobre.setMnemonic('o');
        jMenuSobre.setText("Sobre");
        jMenuSobre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItemAtalhos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemAtalhos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/link 20x20.png"))); // NOI18N
        jMenuItemAtalhos.setText("Atalhos");
        jMenuItemAtalhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtalhosActionPerformed(evt);
            }
        });
        jMenuItemAtalhos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItemAtalhosKeyPressed(evt);
            }
        });
        jMenuSobre.add(jMenuItemAtalhos);

        jMenuItemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        jMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about 20x20.png"))); // NOI18N
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuSobre.add(jMenuItemSobre);

        jMenuBarMenus.add(jMenuSobre);

        setJMenuBar(jMenuBarMenus);

        getAccessibleContext().setAccessibleDescription("Gerenciador");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    //Permite abrir a tela de visualização com click duplo no item
    //private void cliqueDuplo(){
    //    jListSenhasCadastradas.addMouseListener(new MouseAdapter() {
    //        public void mouseClicked(MouseEvent evt) {
    //            if (evt.getClickCount() == 2){
    //                //visualizar();
    //            }
    //        }          
    //    });
    //}
    
    //Cria a tela de gerenciamento de usuário
    private void gestão_de_Usuário(){
        Gerenciar_User gerenciar_User_Frame = new Gerenciar_User(userLogado);
        gerenciar_User_Frame.getContentPane().setLayout(new BorderLayout());
        gerenciar_User_Frame.setLocationRelativeTo(null);
        gerenciar_User_Frame.setResizable(false);
        gerenciar_User_Frame.setVisible(true);
        gerenciar_User_Frame.setAlwaysOnTop(true);   
    }
    
    //Cria a tela de login
    private void login(){
        //Loginfra logindialogo = new Login(this,true);
        Login logindialogo = new Login();
        logindialogo.setLocationRelativeTo(null);
        logindialogo.setResizable(false);
        logindialogo.setVisible(true);    
    }
    
    private void jMenuItemAtalhosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItemAtalhosKeyPressed
    }//GEN-LAST:event_jMenuItemAtalhosKeyPressed
    
    private void jMenuItemAtalhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtalhosActionPerformed
        //Chama a janela que lista os atalhos do programa
        new controladorAtalhos ();
    }//GEN-LAST:event_jMenuItemAtalhosActionPerformed
    
    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        //Cria a janela sobre do programa
        new controladorSobre ();
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemBotão_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBotão_SairActionPerformed
        //Encerra o programa
        System.exit(0);
    }//GEN-LAST:event_jMenuItemBotão_SairActionPerformed

    private void jMenuItemTrocar_UsuárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTrocar_UsuárioActionPerformed
        //Descarta a tela atual
        this.dispose();
        //Invoca a tela de login
        login();
    }//GEN-LAST:event_jMenuItemTrocar_UsuárioActionPerformed

    private void jMenuItemGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarActionPerformed
        gestão_de_Usuário();
        
    }//GEN-LAST:event_jMenuItemGerenciarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        //Encerra o programa
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Blu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Blu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Blu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Blu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                String nomeUser = null;
                @SuppressWarnings("unused")
				Blu JanelaBlu =  new Blu(nomeUser);
                //JanelaBlu.setLayout(new BorderLayout());
                //JanelaBlu.setLocationRelativeTo(null);
                //JanelaBlu.setResizable(false);
                //JanelaBlu.setVisible(true);
            }
        });
    }
    javax.swing.JButton jButtonSair;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabelFundoListagem;
    javax.swing.JMenuBar jMenuBarMenus;
    javax.swing.JMenuItem jMenuItemAtalhos;
    javax.swing.JMenuItem jMenuItemBotão_Sair;
    javax.swing.JMenuItem jMenuItemGerenciar;
    javax.swing.JMenuItem jMenuItemSobre;
    javax.swing.JMenuItem jMenuItemTrocar_Usuário;
    javax.swing.JMenu jMenuMenuUsuário;
    javax.swing.JMenu jMenuSobre;
    javax.swing.JPanel jPanelBotões;
    javax.swing.JPanel jPanelListagem;
    javax.swing.JScrollPane jScrollPaneListadeSenhas;
    // End of variables declaration//GEN-END:variables
}
