package interfaces;

import entidade.Usuário;
import controle.ControleTamanhoTexto;
import static entidade.Usuário.buscar_Usuário_e_PK;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;

import java.net.URL;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.InputMap;
import javax.swing.JComponent;

import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Cassiano Rogério
 */
@SuppressWarnings("serial")
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    //public Login(java.awt.Frame parent, boolean modal) {
    public Login() {
        URL url = this.getClass().getResource("/images/key 20x20.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEtiquetaseCampos = new javax.swing.JPanel();
        jPanelLabels = new javax.swing.JPanel();
        jLabelKey = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jPanelCamposdeDados = new javax.swing.JPanel();
        jPasswordFieldKey = new javax.swing.JPasswordField();
        jFormattedTextFieldUser = new javax.swing.JFormattedTextField();
        jPanelBotões = new javax.swing.JPanel();
        jButtonNovoUser = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Note");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanelEtiquetaseCampos.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabelKey.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelKey.setText("Senha");

        jLabelUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUser.setText("Usuário");

        javax.swing.GroupLayout jPanelLabelsLayout = new javax.swing.GroupLayout(jPanelLabels);
        jPanelLabelsLayout.setHorizontalGroup(
        	jPanelLabelsLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanelLabelsLayout.createSequentialGroup()
        			.addGap(11)
        			.addGroup(jPanelLabelsLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabelUser)
        				.addComponent(jLabelKey, Alignment.TRAILING)))
        );
        jPanelLabelsLayout.setVerticalGroup(
        	jPanelLabelsLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanelLabelsLayout.createSequentialGroup()
        			.addComponent(jLabelUser, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabelKey)
        			.addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelLabels.setLayout(jPanelLabelsLayout);

        jPasswordFieldKey.setDocument( new ControleTamanhoTexto(30) );
        jPasswordFieldKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldKeyActionPerformed(evt);
            }
        });

        jFormattedTextFieldUser.setDocument( new ControleTamanhoTexto(30) );
        jFormattedTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldUserActionPerformed(evt);
            }
        });

        jButtonNovoUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovoUser.setMnemonic('N');
        jButtonNovoUser.setText("Novo Usúario");
        jButtonNovoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoUserActionPerformed(evt);
            }
        });

        jButtonEntrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEntrar.setMnemonic('e');
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setMnemonic('c');
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        getContentPane().add(jPanelEtiquetaseCampos);
        GroupLayout gl_jPanelBotões = new GroupLayout(jPanelBotões);
        gl_jPanelBotões.setHorizontalGroup(
        	gl_jPanelBotões.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanelBotões.createSequentialGroup()
        			.addGap(20)
        			.addComponent(jButtonNovoUser)
        			.addGap(6)
        			.addComponent(jButtonEntrar)
        			.addGap(6)
        			.addComponent(jButtonCancelar))
        );
        gl_jPanelBotões.setVerticalGroup(
        	gl_jPanelBotões.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanelBotões.createSequentialGroup()
        			.addGap(11)
        			.addGroup(gl_jPanelBotões.createParallelGroup(Alignment.LEADING)
        				.addComponent(jButtonNovoUser)
        				.addComponent(jButtonEntrar)
        				.addComponent(jButtonCancelar)))
        );
        jPanelBotões.setLayout(gl_jPanelBotões);
        GroupLayout gl_jPanelCamposdeDados = new GroupLayout(jPanelCamposdeDados);
        gl_jPanelCamposdeDados.setHorizontalGroup(
        	gl_jPanelCamposdeDados.createParallelGroup(Alignment.LEADING)
        		.addComponent(jFormattedTextFieldUser, GroupLayout.PREFERRED_SIZE, 242, GroupLayout.PREFERRED_SIZE)
        		.addComponent(jPasswordFieldKey, GroupLayout.PREFERRED_SIZE, 242, GroupLayout.PREFERRED_SIZE)
        );
        gl_jPanelCamposdeDados.setVerticalGroup(
        	gl_jPanelCamposdeDados.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanelCamposdeDados.createSequentialGroup()
        			.addGap(11)
        			.addComponent(jFormattedTextFieldUser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(11)
        			.addComponent(jPasswordFieldKey, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        jPanelCamposdeDados.setLayout(gl_jPanelCamposdeDados);
        GroupLayout gl_jPanelEtiquetaseCampos = new GroupLayout(jPanelEtiquetaseCampos);
        gl_jPanelEtiquetaseCampos.setHorizontalGroup(
        	gl_jPanelEtiquetaseCampos.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanelEtiquetaseCampos.createSequentialGroup()
        			.addGap(10)
        			.addComponent(jPanelLabels, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(6)
        			.addComponent(jPanelCamposdeDados, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        		.addGroup(gl_jPanelEtiquetaseCampos.createSequentialGroup()
        			.addGap(22)
        			.addComponent(jPanelBotões, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        gl_jPanelEtiquetaseCampos.setVerticalGroup(
        	gl_jPanelEtiquetaseCampos.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanelEtiquetaseCampos.createSequentialGroup()
        			.addGroup(gl_jPanelEtiquetaseCampos.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanelLabels, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jPanelCamposdeDados, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(6)
        			.addComponent(jPanelBotões, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        jPanelEtiquetaseCampos.setLayout(gl_jPanelEtiquetaseCampos);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        //Encerra o programa
        System.exit(0);  
    }//GEN-LAST:event_jButtonCancelarActionPerformed

  //Cria a janela de novo cadastro de senha
    private void Cadastrar(){
        //Criar uma nova janela, para adicionar dados
        Cadastrar cadastrardialogo = new Cadastrar(this,true);
        cadastrardialogo.setLocationRelativeTo(null);
        cadastrardialogo.setResizable(false);
        cadastrardialogo.setVisible(true);
    }
    
    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        //Captura os dados informados pelo usuário
        Usuário dados = capturaNomeSenha();
        if (dados==null) {
            JOptionPane.showMessageDialog(this, "Informe o nome de Usuário e Senha.", "Atenção",
                    JOptionPane.ERROR_MESSAGE);
        }
        //Caso o usuário e senha tenham sido informados na tela de login, irá buscar se o usuário existe no banco
        else if(dados!=null){
            Usuário dadosBuscaBD;
            String userInformado;
            String keyInformada, keyBanco;
            //Busca se o usuário existe, caso não exista terá null como retorno
            if ((dadosBuscaBD = buscar_Usuário_e_PK(dados.getusuário()))==null) {
                JOptionPane.showMessageDialog(this, "User não cadastrado.", "Atenção",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            //Caso o usuário exista no banco, irá testar a senha
            else{
                //Dados informados pelo usuário solicitando o login
                userInformado = dados.getusuário();
                //Senha é encrtiptada para testar a compatil]bilidade com a armazenada no banco
                keyInformada = entidade.EncriptaSenha_SHA256.encripta(dados.getsenha());

                keyBanco = dadosBuscaBD.getsenha();

                //Testa se a senha informada é a mesma armazenada no banco, se sim executa o F5enha
                if (keyInformada.equals(keyBanco)==true){
                    //Descarta a tela de login e executa o F5enha
                    this.dispose();
                    F5enha(userInformado);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Senha incorreta.", "Atenção",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonNovoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoUserActionPerformed
        Cadastrar();
    }//GEN-LAST:event_jButtonNovoUserActionPerformed

    private void jPasswordFieldKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyActionPerformed
        //Quando estiver no campo de texto da senha permite confirmar usando a tecla enter
        jButtonEntrar.doClick();
    }//GEN-LAST:event_jPasswordFieldKeyActionPerformed

    private void jFormattedTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldUserActionPerformed
        //Pula para o campo de senha
        jPasswordFieldKey.requestFocus();
    }//GEN-LAST:event_jFormattedTextFieldUserActionPerformed

    //Permitir fechar a Janela com a tecla Esc
    @Override
    protected JRootPane createRootPane() {
        JRootPane rootPane = new JRootPane();
        KeyStroke stroke = KeyStroke.getKeyStroke("ESCAPE");
        Action actionListener;
        actionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) { 
                //setVisible(false);
                //Encerra o programa
                System.exit(0);  
            } 
        };
        InputMap inputMap = rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(stroke, "ESCAPE");
        rootPane.getActionMap().put("ESCAPE", actionListener);
        return rootPane;
    }
    
    public Usuário capturaNomeSenha(){
        //Usuário dados = null;
        Usuário dados = new Usuário(null,null,null);
        
        //Captura o nome de usuário digitado
        dados.setusuário(jFormattedTextFieldUser.getText());
        //Converte os dados de usuário para caixa baixa(minusculo)
        dados.setusuário(dados.getusuário().toLowerCase());
        
        //Captura a senha digitada
        char[] PassWord =  jPasswordFieldKey.getPassword();
        //Converte a senha em String
        dados.setsenha(String.valueOf(PassWord));
        
        if ((dados.getusuário().isEmpty()==true) && (dados.getsenha().isEmpty()==true)) {
            System.out.println("user e senha vazios");
            return null;
        }
        if (dados.getusuário().isEmpty()==true) {
            System.out.println("user vazio");
            return null;
        }
        if (dados.getsenha().isEmpty()==true) {
            System.out.println("senha vazia");
            return null;
        }
        return dados;
    }
    
    //Cria a tela de login
    private void F5enha(String nomeUser){
        Blu JanelaBlu =  new Blu(nomeUser);
        //JanelaBlu.setLayout(new BorderLayout());
        //JanelaBlu.setLocationRelativeTo(null);
        //JanelaBlu.setResizable(false);
        JanelaBlu.setExtendedState(MAXIMIZED_BOTH);
        JanelaBlu.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login TelaLogin = new Login();
                TelaLogin.getContentPane().setLayout(new BorderLayout());
                TelaLogin.setLocationRelativeTo(null);
                TelaLogin.setResizable(false);
                TelaLogin.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonNovoUser;
    private javax.swing.JFormattedTextField jFormattedTextFieldUser;
    private javax.swing.JLabel jLabelKey;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanelBotões;
    private javax.swing.JPanel jPanelCamposdeDados;
    private javax.swing.JPanel jPanelEtiquetaseCampos;
    private javax.swing.JPanel jPanelLabels;
    private javax.swing.JPasswordField jPasswordFieldKey;
    // End of variables declaration//GEN-END:variables
}
